40_Programming_with_SOFA/10_Start_coding/70_Components_API/40_Events_in_SOFA.md

add information related to events. Press Ctrl key is needed to receive mouse/key events

[Events] add information, press Ctrl key is needed for receiveing events

---

40_Programming_with_SOFA/10_Start_coding/30_Create_your_component.md
40_Programming_with_SOFA/10_Start_coding/70_Components_API/10_Components_and_Datas.md

Hi,
Being bored at our bi-monthly Sofa workgroups I thought I could write a little bit of documentation over the use of Engine components...
Please review and give me some feedback if you see anything missing / wrong.. =)

DataEngine doc

---

30_Using_SOFA/30_Optional_Features/30_Python_scripting.md

Update of the documentary to the current state of the scn2python script and additional paragraph on the usage of command line arguments.

Minor changes and info on command line arguments

---

10_Getting_Started/20_Build/10_Linux.md
10_Getting_Started/20_Build/20_MacOS.md
10_Getting_Started/20_Build/30_Windows.md

Further to remarks on issue #34 
Do you agree @guparan ?

Add compatibility information for Eigen

---

35_Plugins/20_Build_a_plugin_from_sources.md

[Build plugin] Add out-of-tree build

---

10_Getting_Started/20_Build/10_Linux.md

Some updates relative to my weekend experience

Update Linux compilation page with 3.8 python and more

---

10_Getting_Started/20_Build/10_Linux.md

Further to my latest compilation

update compilation instruction for Linux

---

15_Using_SOFA/32_Performances/20_Improve_performances.md

Add a section on model order reduction in the page describing techniques to improve the performances

A word on model order reduction

---

50_Contributing_to_SOFA/45_Lifecycle_mechanisms.md

Just pushing the document written during STC\#12 and STC\#13

Add new page on lifecycle further to STC#13

---

50_Contributing_to_SOFA/45_Lifecycle_mechanisms.md

Further to [#3563](https://github.com/sofa-framework/sofa/pull/3563)

Update info about how to handle the change of the Data default value

---

50_Contributing_to_SOFA/45_Lifecycle_mechanisms.md

I could not bear this page, now with tables, it's readable !
I  added the doc on Data removal/deprecation.
Do not hesitate to point me any missing info for the lifecycle
pour une belle lecture :eyeglasses: https://github.com/sofa-framework/doc/blob/01bf0b50295d1e9c414d7b51d387ad1a772374ec/50_Contributing_to_SOFA/45_Lifecycle_mechanisms.md

Update Lifecycle Mechanism with table and Deprecated/RemovedData

---

10_Getting_Started/20_Build/10_Linux.md
10_Getting_Started/20_Build/20_MacOS.md
10_Getting_Started/20_Build/30_Windows.md

Related to https://github.com/sofa-framework/sofa/pull/4586

update cmake minimal versions for OS

---

10_Getting_Started/20_Build/30_Windows.md

Remove note specifying that Qt6 is not fully supported

Qt6 for Windows

---

30_Components/35_MechanicalLoad/10_ConicalForceField.md

This is to test what it would look like on the website.
To compare to https://alxbilger.github.io/SofaDocGenerator/conicalforcefield.html

Introduce a single example of an automatically generated documentation of a component

---

10_Getting_Started/20_Build/20_MacOS.md
10_Getting_Started/20_Build/30_Windows.md

Further to feedback from users at SAW2024

Update build instructions

---

README.md

Some markdown parsers prefer like that

add empty lines and 4 spaces indentation

---

.github/workflows/doc.yml
README.md
script/generate_nav.py
script/merge_docs.py
script/title_metadata.py
src/Main.cpp

- Schedule doc generation every day
- add more example folders
- Documentation of scripts, and additions in readme file

Add details

---

.github/workflows/trigger_doc_gen.yml

Add action triggering the doc generation in the **gen** branch
Along with #128

Add action triggering the doc generation

---

mkdocs/mkdocs.yml

GHA workflow does not seem to be daily triggered despite :
```
schedule:
- cron: '0 0 * * *'    # every day at midnight
```
This PR is just a minor change to test the push workflow

Minor change to trigger workflow

---

script/generate_nav.py

Replaces https://github.com/sofa-framework/doc/pull/132

Rename files and folders to remove suffix

---

script/generate_nav.py

In order to keep compatibility with older doc paths, make all url lowercase

Make all url lowercase

---

30_Components/25_Engine/20_Select/34_SubsetTopology.md

The file is renamed according to the component name

Change case

---

.github/workflows/doc.yml

- add the missing contributing 
- add a link to the example file on GitHub for each component

[workflow] Add contributing from SOFA sources

---

35_Plugins/20_Build_a_plugin_from_sources.md

This was required to build the DocGenerator project aside SOFA
I let you @bakpaul @fredroy share some feedback about it

Suggest SOFA_ROOT env var when buidling a plugin

---

script/pipeline.py

Update pipeline.py to add the contributing file

Add contributing file

---

10_Getting_Started/20_Build/10_Linux.md

Close #109 
Thanks to @lamriaimen, @alxbilger and @fredroy for this topic

Mention qtwayland support

---

30_Components/50_Mapping/NonLinear/AreaMapping.md

This PR comes with https://github.com/sofa-framework/sofa/pull/4898

doc for AreaMapping

---

30_Components/40_ODESolver/20_Backward/50_StaticSolver.md

The Latex command did not end correctly

Fix Newton-Raphson equation

---

.github/workflows/doc.yml
mkdocs/mkdocs.yml

25 04 fix doc build

---

10_Getting_Started/20_Build/50_Activate_Plugins.md
35_Plugins/45_Suported_Plugins_List.md

Add space before lists to fix markdown

Fix markdown of lists
